-- Migrasi Skema PropHub Supabase

-- 1. Buat custom types (Enums)
  CREATE TYPE user_role AS ENUM ('tenant', 'owner', 'admin');
  CREATE TYPE property_type AS ENUM ('Kos', 'Kontrakan', 'Rumah');
  CREATE TYPE room_type AS ENUM ('Single', 'Double');
  CREATE TYPE property_status AS ENUM ('Available', 'Occupied', 'Under Contract');
  CREATE TYPE payment_scheme_type AS ENUM ('full', 'dp30', 'dp50');
  CREATE TYPE transaction_status AS ENUM ('pending', 'survey_scheduled', 'paid', 'cancelled');

-- 2. Buat tabel profiles (extending auth.users)
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  phone_number TEXT,
  role user_role DEFAULT 'tenant'::user_role,
  avatar_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- RLS profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- 3. Buat tabel properties
CREATE TABLE public.properties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  price_per_month NUMERIC NOT NULL,
  location TEXT NOT NULL,
  type property_type NOT NULL,
  room_type room_type,
  status property_status DEFAULT 'Available'::property_status,
  service_fee NUMERIC DEFAULT 0,
  maintenance_fee NUMERIC DEFAULT 0,
  facilities JSONB DEFAULT '[]'::jsonb,
  amenities JSONB DEFAULT '[]'::jsonb,
  rules JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- RLS properties
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Properties are viewable by everyone." ON public.properties FOR SELECT USING (true);
CREATE POLICY "Owners can insert properties." ON public.properties FOR INSERT WITH CHECK (auth.uid() = owner_id);
CREATE POLICY "Owners can update own properties." ON public.properties FOR UPDATE USING (auth.uid() = owner_id);
CREATE POLICY "Owners can delete own properties." ON public.properties FOR DELETE USING (auth.uid() = owner_id);

-- 4. Buat tabel property_images
CREATE TABLE public.property_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id BIGINT REFERENCES public.properties(id) ON DELETE CASCADE NOT NULL,
  image_url TEXT NOT NULL,
  is_primary BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- RLS property_images
ALTER TABLE public.property_images ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Images are viewable by everyone." ON public.property_images FOR SELECT USING (true);
-- Note: Insert/Update/Delete would need joining with properties to check owner_id. 
-- For simplicity in prototype, we'll let authenticated users manage images for properties they own.

-- 5. Buat tabel saved_properties
CREATE TABLE public.saved_properties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  property_id BIGINT REFERENCES public.properties(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  UNIQUE(user_id, property_id)
);

-- RLS saved_properties
ALTER TABLE public.saved_properties ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own saved properties." ON public.saved_properties FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own saved properties." ON public.saved_properties FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own saved properties." ON public.saved_properties FOR DELETE USING (auth.uid() = user_id);

-- 6. Buat tabel transactions
CREATE TABLE public.transactions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  tenant_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  property_id BIGINT REFERENCES public.properties(id) ON DELETE RESTRICT NOT NULL,
  duration_months INTEGER NOT NULL,
  payment_method TEXT NOT NULL,
  payment_scheme payment_scheme_type DEFAULT 'full'::payment_scheme_type,
  total_amount NUMERIC NOT NULL,
  paid_amount NUMERIC NOT NULL,
  survey_date DATE,
  survey_time TIME,
  status transaction_status DEFAULT 'pending'::transaction_status,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- RLS transactions
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenants view own transactions." ON public.transactions FOR SELECT USING (auth.uid() = tenant_id);
-- In a full app, owners also need to see transactions for their properties.
CREATE POLICY "Tenants can insert own transactions." ON public.transactions FOR INSERT WITH CHECK (auth.uid() = tenant_id);

-- 7. Trigger untuk otomatis membuat profil saat user baru mendaftar di Auth Supabase
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name)
  VALUES (new.id, new.raw_user_meta_data->>'full_name');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Selesai
